# Generated by Django 2.0.9 on 2018-11-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20181122_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeobserver',
            name='message',
            field=models.CharField(default='', max_length=500),
        ),
    ]
