# Generated by Django 2.0.9 on 2018-11-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_auto_20181122_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeobserver',
            name='message_type',
            field=models.DecimalField(decimal_places=0, default=25, max_digits=2),
        ),
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
