# Generated by Django 2.0.9 on 2018-11-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_auto_20181122_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeobserver',
            name='message_type',
            field=models.DecimalField(decimal_places=0, default=25, max_digits=5),
        ),
    ]
