# Generated by Django 2.0.9 on 2018-11-22 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0005_auto_20181122_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradeobserver',
            name='message_type',
        ),
    ]
