# Generated by Django 2.0.9 on 2018-11-22 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_remove_gradeobserver_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
