# Generated by Django 2.0.9 on 2018-11-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_gradeobserver_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeobserver',
            name='message_type',
            field=models.DecimalField(blank=25, decimal_places=0, default=25, max_digits=5, null=25),
        ),
    ]
