# Generated by Django 2.0.9 on 2018-11-23 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_auto_20181122_2202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textquestion',
            old_name='text',
            new_name='text_question',
        ),
        migrations.RemoveField(
            model_name='textquestion',
            name='close_date',
        ),
    ]
