# Generated by Django 2.0.9 on 2018-11-23 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0011_examquestion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamQuestion',
        ),
    ]
