# Generated by Django 2.0.9 on 2018-11-23 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_module'),
        ('list', '0012_delete_examquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField()),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.SchoolYear')),
            ],
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Exam')),
            ],
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='imagequestion',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='textquestion',
            name='polymorphic_ctype',
        ),
        migrations.RemoveField(
            model_name='textquestion',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='videoquestion',
            name='polymorphic_ctype',
        ),
    ]
